<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('user_details')->insert([
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 1',
                'lname'=> 'juril1',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456781',
                'user_id'=> 2,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'nasipit',
                'brgy'=> 'barangay 1',
                'long'=> '3453',
                'lat'=> '1245'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 2',
                'lname'=> 'joe2',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456782',
                'user_id'=> 3,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'nasipit',
                'brgy'=> 'barangay 2',
                'long'=> '3423',
                'lat'=> '1244'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 3',
                'lname'=> 'juril3',
                'sex'=> 'female',
                'bday'=> '2022-07-04',
                'phone'=> '09123456783',
                'user_id'=> 4,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'nasipit',
                'brgy'=> 'barangay 3',
                'long'=> '3314',
                'lat'=> '1243'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 4',
                'lname'=> 'juril4',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456784',
                'user_id'=> 5,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'carmen',
                'brgy'=> 'barangay 4',
                'long'=> '3314',
                'lat'=> '1242'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 5',
                'lname'=> 'joe5',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456785',
                'user_id'=> 6,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'carmen',
                'brgy'=> 'barangay 5',
                'long'=> '3316',
                'lat'=> '1241'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 6',
                'lname'=> 'juril6',
                'sex'=> 'female',
                'bday'=> '2022-07-04',
                'phone'=> '09123456786',
                'user_id'=> 7,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'butuan',
                'brgy'=> 'barangay 6',
                'long'=> '3317',
                'lat'=> '1247'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 7',
                'lname'=> 'juril7',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456712',
                'user_id'=> 8,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'butuan',
                'brgy'=> 'barangay 7',
                'long'=> '3318',
                'lat'=> '1248'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 8',
                'lname'=> 'joe8',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456714',
                'user_id'=> 9,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'butuan',
                'brgy'=> 'barangay 8',
                'long'=> '3319',
                'lat'=> '1249'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 9',
                'lname'=> 'juril9',
                'sex'=> 'female',
                'bday'=> '2022-07-04',
                'phone'=> '09123456716',
                'user_id'=> 10,
                'region'=> 'caraga',
                'province'=> 'agusan del norte',
                'city'=> 'butuan',
                'brgy'=> 'barangay 9',
                'long'=> '3234',
                'lat'=> '1240'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 10',
                'lname'=> 'juril10',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456234',
                'user_id'=> 11,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'san francisco',
                'brgy'=> 'barangay 10',
                'long'=> '3231',
                'lat'=> '5324'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 11',
                'lname'=> 'joe11',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456266',
                'user_id'=> 12,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'san francisco',
                'brgy'=> 'barangay 11',
                'long'=> '3232',
                'lat'=> '5323'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 12',
                'lname'=> 'juril12',
                'sex'=> 'female',
                'bday'=> '2022-07-04',
                'phone'=> '09123456223',
                'user_id'=> 13,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'san francisco',
                'brgy'=> 'barangay 12',
                'long'=> '3239',
                'lat'=> '5322'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 13',
                'lname'=> 'juril13',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456212',
                'user_id'=> 14,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'prosperidad',
                'brgy'=> 'barangay 13',
                'long'=> '5123',
                'lat'=> '5321'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 14',
                'lname'=> 'joe14',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456256',
                'user_id'=> 15,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'prosperidad',
                'brgy'=> 'barangay 14',
                'long'=> '5122',
                'lat'=> '5326'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 15',
                'lname'=> 'juril15',
                'sex'=> 'female',
                'bday'=> '2022-07-04',
                'phone'=> '09123452342',
                'user_id'=> 16,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'prosperidad',
                'brgy'=> 'barangay 15',
                'long'=> '5125',
                'lat'=> '5327'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 16',
                'lname'=> 'juril16',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123435123',
                'user_id'=> 17,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'bayugan',
                'brgy'=> 'barangay 16',
                'long'=> '5126',
                'lat'=> '5328'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'farmer 17',
                'lname'=> 'joe17',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123438678',
                'user_id'=> 18,
                'region'=> 'caraga',
                'province'=> 'agusan del sur',
                'city'=> 'bayugan',
                'brgy'=> 'barangay 17',
                'long'=> '5127',
                'lat'=> '5398'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 1',
                'lname'=> 'joe1',
                'sex'=> null,
                'bday'=> '2022-07-04',
                'phone'=> '09123438688',
                'user_id'=> 19,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'cagwait',
                'brgy'=> 'barangay 1A',
                'long'=> '5128',
                'lat'=> '1533'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 2',
                'lname'=> 'joe2',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123458967',
                'user_id'=> 20,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'cagwait',
                'brgy'=> 'barangay 1B',
                'long'=> '5121',
                'lat'=> '1532'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 3',
                'lname'=> 'joe3',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123458345',
                'user_id'=> 21,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'cagwait',
                'brgy'=> 'barangay 1C',
                'long'=> '51210',
                'lat'=> '1531'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 4',
                'lname'=> 'joe4',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123458252',
                'user_id'=> 22,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'bislig',
                'brgy'=> 'barangay 1D',
                'long'=> '5120',
                'lat'=> '1535'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 5',
                'lname'=> 'joe5',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122352366',
                'user_id'=> 23,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'bislig',
                'brgy'=> 'barangay 1E',
                'long'=> '9843',
                'lat'=> '1536'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 6',
                'lname'=> 'joe6',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122358678',
                'user_id'=> 24,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'tandag',
                'brgy'=> 'barangay 1F',
                'long'=> '9841',
                'lat'=> '1537'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 7',
                'lname'=> 'joe7',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122423667',
                'user_id'=> 25,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'tandag',
                'brgy'=> 'barangay 1G',
                'long'=> '9842',
                'lat'=> '1538'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 8',
                'lname'=> 'joe8',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122427567',
                'user_id'=> 26,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'tandag',
                'brgy'=> 'barangay 1H',
                'long'=> '9846',
                'lat'=> '1539'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 9',
                'lname'=> 'joe9',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122427675',
                'user_id'=> 27,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'tandag',
                'brgy'=> 'barangay 1I',
                'long'=> '9847',
                'lat'=> '1530'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 10',
                'lname'=> 'joe10',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122427688',
                'user_id'=> 28,
                'region'=> 'caraga',
                'province'=> 'surigao del sur',
                'city'=> 'barobo',
                'brgy'=> 'barangay 1J',
                'long'=> '9848',
                'lat'=> '9083'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 11',
                'lname'=> 'joe11',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122427681',
                'user_id'=> 29,
                'region'=> 'caraga',
                'province'=> 'surigao del norte',
                'city'=> 'tagana-an',
                'brgy'=> 'barangay 1K',
                'long'=> '9849',
                'lat'=> '9081'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 12',
                'lname'=> 'joe12',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122427682',
                'user_id'=> 30,
                'region'=> 'caraga',
                'province'=> 'surigao del norte',
                'city'=> 'tagana-an',
                'brgy'=> 'barangay 1L',
                'long'=> '9840',
                'lat'=> '9082'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 13',
                'lname'=> 'joe13',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09122678678',
                'user_id'=> 31,
                'region'=> 'caraga',
                'province'=> 'surigao del norte',
                'city'=> 'surigao city',
                'brgy'=> 'barangay 1M',
                'long'=> '9523',
                'lat'=> '9087'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 14',
                'lname'=> 'joe14',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456789',
                'user_id'=> 32,
                'region'=> 'caraga',
                'province'=> 'surigao del norte',
                'city'=> 'surigao city',
                'brgy'=> 'barangay 1N',
                'long'=> '9527',
                'lat'=> '9088'
            ],
            [
                'created_at'=> \Carbon\Carbon::now(),
                'updated_at'=> \Carbon\Carbon::now(),
                'fname'=> 'trader 15',
                'lname'=> 'joe15',
                'sex'=> 'male',
                'bday'=> '2022-07-04',
                'phone'=> '09123456780',
                'user_id'=> 33,
                'region'=> 'caraga',
                'province'=> 'surigao del norte',
                'city'=> 'surigao city',
                'brgy'=> 'barangay 1O',
                'long'=> '8945',
                'lat'=> '3442'
            ],
             
        ]);
    }
}
