<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'email' => 'agriboostbxu@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'Agrihub',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer1@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer2@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer3@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer4@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer5@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer6@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer7@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer8@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer9@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer10@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer11@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer12@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer13@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer14@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer15@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer16@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_farmer17@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'farmer',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader1@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader2@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader3@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader4@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader5@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader6@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader7@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader8@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader9@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader10@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'approved',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader11@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader12@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader13@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader14@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],
            [
                'email' => 'agriboost_trader15@gmail.com',
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'remember_token' => null,
                // 'current_team_id' => null,
                'profile_photo_path' => null,
                'user_type' => 'trader',
                'status' => 'pending',
                'created_at' => Carbon::today()->subDays(rand(0, 365)),
                'updated_at' => Carbon::today()->subDays(rand(0, 365)),
            ],

             
        ]);
    }
}
